### ISSUE TITLE
建议修改翻译

### ISSUE THREAD

**Issue by helingen** [kira-96/Inno-Setup-Chinese-Simplified-Translation#11]
ConfirmUninstall=您确认想要完全删除 %1 及它的所有组件吗？
建议改为：
ConfirmUninstall=您确认想要完全删除 %1 及其所有组件吗？

ApplicationsFound=下列应用程序正在使用的文件需要更新设置。它是建议您允许安装程序自动关闭这些应用程序。
建议改为：
ApplicationsFound=以下应用程序正在使用需要由安装程序更新的文件。建议您允许安装程序自动关闭这些应用程序。

ApplicationsFound2=下列应用程序正在使用的文件需要更新设置。它是建议您允许安装程序自动关闭这些应用程序。安装完成后，安装程序将尝试重新启动应用程序。
建议改为：
ApplicationsFound2=以下应用程序正在使用需要由安装程序更新的文件。建议您允许安装程序自动关闭这些应用程序。安装完成后，安装程序将尝试重新启动这些应用程序。

**Comment by pzhlkj6612** [comment]
你好。

我发现当前的 [ApplicationsFound](https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/blob/1ea714702c999b86c7b75b3fa5a645824a7013ec/ChineseSimplified.isl#L242) 与你的建议相同：

```
以下应用程序正在使用需要由安装程序更新的文件。建议您允许安装程序自动关闭这些应用程序。
```

<br>

当前的 [ApplicationsFound2](https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/blob/1ea714702c999b86c7b75b3fa5a645824a7013ec/ChineseSimplified.isl#L243) 为：

```
以下应用程序正在使用需要由安装程序更新的文件。建议您允许安装程序自动关闭这些应用程序。安装完成后，安装程序将尝试重新启动应用程序。
```

与你的建议对比：

```diff
  以下应用程序正在使用需要由安装程序更新的文件。建议您允许安装程序自动关闭这些应用程序。安装完成后，
- 安装程序将尝试重新启动应用程序。
+ 安装程序将尝试重新启动这些应用程序。
```

<br>

提交 a14582f39fd23d858ba1138b992248aa7312af6d 包含对这两个字符串的修改。你是否忘记更新本地代码了？

**Comment by helingen** [comment]
我当时用的最新的，这是一个修改建议，小的修改建议

**Comment by helingen** [comment]
@pzhlkj6612 我用的最新的，这是一个修改建议，小的修改建议

**Comment by pzhlkj6612** [comment]
@helingen 你好。
我没有否定你的修改建议，也没有认为小的修改建议不可以，我是说：

1. 在[第一条](https://github.com/kira-96/Inno-Setup-Chinese-Simplified-Translation/issues/11#issue-1111801137)中，你提供了 `ApplicationsFound` 和 `ApplicationsFound2` 的原文与建议，但这个原文只存在于较 a14582f39fd23d858ba1138b992248aa7312af6d 更老的版本。如果你使用的是最新的翻译，那么，
    1. 你不应该看到更老的原文，同时，
    2. 你应该基于最新的原文提出修改建议。
2. 最新的 `ApplicationsFound` 与你建议的完全一致，不需要修改，因此这个建议是多余的。

<br>

基于最新的翻译，你的建议应该是：

> ConfirmUninstall=您确认想要完全删除 %1 及它的所有组件吗？
> 建议改为：
> ConfirmUninstall=您确认想要完全删除 %1 及其所有组件吗？
> 
> ApplicationsFound2=以下应用程序正在使用需要由安装程序更新的文件。建议您允许安装程序自动关闭这些应用程序。安装完成后，安装程序将尝试重新启动应用程序。
> 建议改为：
> ApplicationsFound2=以下应用程序正在使用需要由安装程序更新的文件。建议您允许安装程序自动关闭这些应用程序。安装完成后，安装程序将尝试重新启动这些应用程序。

<br>

如果我表达得不清楚或说错了什么，请你提出来，谢谢！

**Comment by kira-96** [comment]
因为最初的版本是机翻的，所以有些地方可能不准确。非常感谢你们的意见，我会认真考虑和修改。
