### ISSUE TITLE
在哪个文件里加你那个[Language] 节点

### ISSUE THREAD

**Issue by fjwgrace** [kira-96/Inno-Setup-Chinese-Simplified-Translation#3]
在哪个文件里加你那个[Language] 节点？

**Comment by kira-96** [comment]
如果你是通过脚本向导创建的脚本，向导会自动生成`[Languages]`部分。在跟随脚本向导创建的过程中，会出现**Languages**选项，你可以直接勾选**Chinese Simplified**（前提是你已经将ChineseSimplified.isl文件放到正确的目录下）。  
如果你是新建的空白脚本文件，那么你需要手动添加`[Languages]`部分，在脚本的任意位置都可以。

**Comment by kira-96** [comment]
我已经更新了README，尽量详细说明了用法。
