### ISSUE TITLE
5.5.3+版本的在win10上制作的setup安装包运行后全是乱码

### ISSUE THREAD

**Issue by anzhen9** [kira-96/Inno-Setup-Chinese-Simplified-Translation#7]
5.5.3+版本的在win10上制作的setup安装包运行后全是乱码

![image](https://user-images.githubusercontent.com/23622902/119797531-e5bfd800-bf0c-11eb-8132-cf5e06a50dca.png)
![image](https://user-images.githubusercontent.com/23622902/119797692-0720c400-bf0d-11eb-8151-b832bc736fa2.png)

**Comment by pzhlkj6612** [comment]
你好。我没有遇到过这个问题，但是我猜是没有区分 Unicode 与非 Unicode 版本的 Inno Setup 的做法引起了这个问题。你用的是什么版本的 Inno Setup ？

如果是 5.5.3 ，你可以分别尝试这俩：

- https://files.jrsoftware.org/is/5/isetup-5.5.3.exe
- https://files.jrsoftware.org/is/5/isetup-5.5.3-unicode.exe

从 Inno Setup 6 开始，就只有 Unicode 版本的了：

> **Change in default behavior:** Starting with Inno Setup 6 there's only one version available: Unicode Inno Setup.
> 
> https://jrsoftware.org/isdl.php

**Comment by anzhen9** [comment]
需要兼容XP系统才用的5.x版本的，刚才测试了5.5.3-unicode，打完的包也是一样乱码的

**Comment by anzhen9** [comment]
可能是isl文件的关系，我是直接复制的文件内容新建的，我再试试直接下载的文件

**Comment by anzhen9** [comment]
isl的问题，我直接复制的文件内容然后新建的文件，更换了直接下载的文件之后好了。。。

**Comment by pzhlkj6612** [comment]
解决了就好。

看上去，你之前新建的文件的编码没有被正确地设置。 .isl 的编码是 UTF-8 with BOM ，有时间的话你可以做一做验证。
