### ISSUE TITLE
修改一个词

### ISSUE THREAD

**Issue by helingen** [kira-96/Inno-Setup-Chinese-Simplified-Translation#8]
#### 问题描述
SelectDirLabel3=安装程序将安装 [name] 到下列文件夹中。”下列“感觉是多个的意思
#### 建议
SelectDirLabel3=安装程序将安装 [name] 到下面文件夹中。

**Comment by helingen** [comment]
SelectStartMenuFolderLabel3=安装程序将在下列开始菜单文件夹中创建程序的快捷方式。建议改为：
SelectStartMenuFolderLabel3=安装程序将在下面开始菜单文件夹中创建程序的快捷方式。

**Comment by helingen** [comment]
InvalidPath=您必须输入一个带驱动器卷标的完整路径，例如：%n%nC:\APP%n%n或下列形式的UNC路径：%n%n\\server\share
英文版：
InvalidPath=You must enter a full path with drive letter; for example:%n%nC:\APP%n%nor a UNC path in the form:%n%n\\server\share
建议翻译为：
InvalidPath=您必须输入一个带驱动器卷标的完整路径，例如：%n%nC:\APP%n%n或UNC路径，格式为：%n%n\\server\share

**Comment by pzhlkj6612** [comment]
> #### 问题描述
> SelectDirLabel3=安装程序将安装 [name] 到下列文件夹中。”下列“感觉是多个的意思
> 
> #### 建议
> SelectDirLabel3=安装程序将安装 [name] 到下面文件夹中。

我的建议是：

```diff
  SelectDirLabel3=安装程序将安装 [name] 到
- 下面文件夹中。
+ 下面的文件夹中。
```

```diff
  SelectDirLabel3=安装程序将安装 [name] 到
- 下面文件夹中。
+ 以下文件夹中。
```

```diff
  SelectDirLabel3=安装程序将安装 [name] 到
- 下面文件夹中。
+ 以下的文件夹中。
```

**Comment by pzhlkj6612** [comment]
> InvalidPath=您必须输入一个带驱动器卷标的完整路径，例如：%n%nC:\APP%n%n或下列形式的UNC路径：%n%n\server\share
> 英文版：
> InvalidPath=You must enter a full path with drive letter; for example:%n%nC:\APP%n%nor a UNC path in the form:%n%n\server\share
> 建议翻译为：
> InvalidPath=您必须输入一个带驱动器卷标的完整路径，例如：%n%nC:\APP%n%n或UNC路径，格式为：%n%n\server\share

@helingen ，你可以使用 Markdown 的代码块格式以避免反斜杠转义。请看例子：

不使用代码块格式：

```markdown
InvalidPath=... or a UNC path in the form:%n%n\\server\share
```

渲染后：

> InvalidPath=... or a UNC path in the form:%n%n\\server\share

使用代码块格式：

```markdown
    ```INI
    InvalidPath=... or a UNC path in the form:%n%n\\server\share
    ```
```

渲染后：

```INI
InvalidPath=... or a UNC path in the form:%n%n\\server\share
```
